"""Migration

Revision ID: af755365edc1
Revises: 6d8d6d53cb98
Create Date: 2025-02-24 13:56:26.418003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af755365edc1'
down_revision = '6d8d6d53cb98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
